name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    env:
      XML2RFC_REFCACHEDIR: .refcache
      VENVDIR: .venv
      BUNDLE_PATH: .gems
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup"
      id: setup
      run: |
        date -u "+::set-output name=date::%FT%T"

    - name: "Cache venv"
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.VENVDIR }}
          ${{ env.BUNDLE_PATH }}
        key: venvcache-${{ steps.setup.outputs.date }}
        restore-keys: venvcache-

    - name: "Cache References"
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.XML2RFC_REFCACHEDIR }}
          .targets.mk
        key: refcache-${{ steps.setup.outputs.date }}
        restore-keys: refcache-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ github.token }}

    - name: "Archive Built Drafts"
      uses: actions/upload-artifact@v2
      with:
        path: |
          draft-*.html
          draft-*.txt
